/* Downloads the three site fonts from Google Fonts as woff2 and writes
   assets/css/fonts.css with LOCAL urls, so the site never calls
   fonts.googleapis.com / fonts.gstatic.com at runtime.
   Important for visitors in Russia, where those hosts are slow/unstable.

   Usage:  node tools/get-fonts.js
   Re-run it whenever a weight or family is added to FAMILIES below.       */
'use strict';

const https = require('https');
const fs = require('fs');
const path = require('path');

const UA = 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 ' +
           '(KHTML, like Gecko) Chrome/124.0 Safari/537.36';

const FAMILIES = [
  'IBM+Plex+Sans+Arabic:wght@400;500;600;700',
  'IBM+Plex+Mono:wght@400;500',
  'Inter:wght@400;500;600;700'
];

const ROOT = path.join(__dirname, '..');
const FONT_DIR = path.join(ROOT, 'assets', 'fonts');
const OUT_CSS = path.join(ROOT, 'assets', 'css', 'fonts.css');

function get(url, ua) {
  return new Promise((resolve, reject) => {
    const req = https.get(url, { headers: { 'User-Agent': ua || UA } }, res => {
      if (res.statusCode >= 300 && res.statusCode < 400 && res.headers.location) {
        return resolve(get(res.headers.location, ua));
      }
      if (res.statusCode !== 200) {
        res.resume();
        return reject(new Error(url + ' -> HTTP ' + res.statusCode));
      }
      const chunks = [];
      res.on('data', c => chunks.push(c));
      res.on('end', () => resolve(Buffer.concat(chunks)));
    });
    req.on('error', reject);
    req.setTimeout(60000, () => req.destroy(new Error('timeout ' + url)));
  });
}

(async () => {
  const cssUrl = 'https://fonts.googleapis.com/css2?' +
    FAMILIES.map(f => 'family=' + f).join('&') + '&display=swap';

  const css = (await get(cssUrl)).toString('utf8');
  const urls = [...new Set((css.match(/https:\/\/fonts\.gstatic\.com\/[^)]+/g) || []))];
  console.log('css bytes:', css.length, '| font files:', urls.length);

  fs.mkdirSync(FONT_DIR, { recursive: true });

  let local = css;
  for (const u of urls) {
    const name = u.replace(/^https:\/\/fonts\.gstatic\.com\//, '')
                   .replace(/[^\w.-]+/g, '_');
    const dest = path.join(FONT_DIR, name);
    if (!fs.existsSync(dest)) {
      const buf = await get(u);
      fs.writeFileSync(dest, buf);
      console.log('  saved', name, buf.length, 'bytes');
    }
    local = local.split(u).join('../fonts/' + name);
  }

  const banner = '/* Generated by tools/get-fonts.js — do not edit by hand.\n' +
                 '   Self-hosted copies of IBM Plex Sans Arabic, IBM Plex Mono, Inter.\n' +
                 '   Licensed under the SIL Open Font License 1.1 (Google Fonts). */\n\n';
  fs.writeFileSync(OUT_CSS, banner + local);
  console.log('wrote', OUT_CSS);

  const total = fs.readdirSync(FONT_DIR).reduce((s, f) =>
    s + fs.statSync(path.join(FONT_DIR, f)).size, 0);
  console.log('assets/fonts:', fs.readdirSync(FONT_DIR).length, 'files,',
              (total / 1024).toFixed(0), 'KB total');
})().catch(e => { console.error('FAILED:', e.message); process.exit(1); });
